apiVersion: v1
kind: Service
metadata:
  name: math-service
spec:
  selector:
    app: math
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math
spec:
  selector:
    matchLabels:
      app: math
  replicas: 4
  template:
    metadata:
      labels:
        app: math
    spec:
      containers:
      - name: math
        image: jsiow002dev/math
        ports:
        - containerPort: 8080